redhat-cop/org

- README.md
- config.yaml
- current.yaml
Initial seed for configurations
> Initial seed

- config.yaml
> Full dump of config file

- config.yaml
Corrections as identified by the peribolos tool
> Corrected membership based on validations

- config.yaml
> More Changes made to the org

- .github/ISSUE_TEMPLATE/become-a-contributor.md
- .github/ISSUE_TEMPLATE/general-suport.md
- .github/ISSUE_TEMPLATE/integrations.md
- .github/ISSUE_TEMPLATE/permissions.md
- .github/ISSUE_TEMPLATE/repository-management.md
- .github/ISSUE_TEMPLATE/team-management.md
> Added GitHub issue templates

- config.yaml
> Adding Petter to infra-ansible, removing Ben

- config.yaml
> GPTE should have write access to lab repos

- config.yaml
Creation of teams to resolve #19
> Team creation for automation CoP

- config.yaml
Added application CoP maintainers as org members as required
> Added application CoP maintainers as org members

- config.yaml
Continued fixing of application cop members
> Continued fixing of application cop members

- config.yaml
> Recreating appdev team

- config.yaml
Full configuration of appdev-cop
> Full configuration of appdev-cop

- config.yaml
Added cpeters to CoP organization to resolve #24
> Added cpeters to CoP organizations

- config.yaml
Added repositories for automation-cop-members team
> Added repositories for automation-cop-members team

- config.yaml
Added jlozadad as maintainer of automation-cop-members to resolve #26
> Added jlozadad as maintainer of automation-cop-members

- config.yaml
> Adding Babylon / DarkTower team and users

- config.yaml
> Add leethomasrh and automate_elk permissions

- .github/ISSUE_TEMPLATE/become-a-contributor.md
- .github/ISSUE_TEMPLATE/general-suport.md
- .github/ISSUE_TEMPLATE/integrations.md
- .github/ISSUE_TEMPLATE/permissions.md
- .github/ISSUE_TEMPLATE/repository-management.md
- .github/ISSUE_TEMPLATE/team-management.md
- config.yaml
Making changes to notify core-team for requests + grant admin access for core-team to the org.
> Adding core-team request notifications and as admins org

- config.yaml
resolves #48 
@fridim @tonykay @jkupferer FYI - please review the permissions ... linked it to the rest of the babylon permissions.
> Adding 'agnosticv' for Babylon team

- config.yaml
> Adding JuozasA to org

- config.yaml
Add marcredhat to CoP members to resolve #51
> Add marcredhat to CoP members

- config.yaml
> Added operators repositories

- config.yaml
Add Ansible Middleware to ansible_middleware_galaxy repo
> Add Ansible Middleware to ansible_middleware_galaxy repo

- config.yaml
resolves #57 
@makentenza please let us know if this is how you envisioned the team structure to be laid out.
> Adding sap-cop team structure

- config.yaml
Add @prakritiverma to the MDT team.
> Add prakriti to mdt team

- config.yaml
Added giofontana to resolve #63
> Added giofontana to CoP members

- config.yaml
> Removed SAP teams

- config.yaml
Added new members to resolve #70 #69 #68 #67
> Added new members to the CoP organization

- config.yaml
New organization user to resolve #69
> New CoP user

- config.yaml
Added must-gather-operator to operators teams for #73
> Added must-gather-operator to operators

- config.yaml
Add repository for k8s_config ansible role.
> Add k8s_config

- config.yaml
> Add anarchy repo

- config.yaml
> Add skypatrolcpt as a merge for uncontained

- OWNERS
- config.yaml
Added CoP Bot account to admin
> Added CoP Bot account to admin

- config.yaml
Removed OpenShift CI robot accounts
> Removed OpenShift CI robot accounts

- config.yaml
Adding permissions for poolboy repository for #89
> Add poolboy repository

- config.yaml
> Add permissions for babylon-events-console

- config.yaml
Added robbbbh as CoP member to resolve #96
> Added robbbbh as CoP member

- config.yaml
Added aglenn360 to CoP members to resolve #99
> Add aglenn360 to CoP members

- config.yaml
Added welshstew to CoP org members to resolve #105
> Added welshstew to CoP org members

- config.yaml
Added seravat to CoP org members to resolve #108
> Added seravat to CoP org members

- config.yaml
Added pamenon to CoP org members, fixes #110
> Added pamenon to CoP org members

- config.yaml
Added jlozadad as Automation CoP mgr, fixes #113
> Added jlozadad as Automation CoP mgr

- config.yaml
Added salar-nabb to CoP org members, fixes #115
> Added salar-nabb to CoP org members

- config.yaml
Add new team and repo for project-initialize-operator, fixes #119, #120, #121
> Add new team and repo for project-initialize-operator

- config.yaml
> Add businessautomation-cop team and repo config

- config.yaml
After all these years you'd think I'd use copy-paste instead of typing in things... :disappointed:
Also changed permissions on the parent team to `read` and let the `-mgrs` team have admin, similar to other teams in our org.
> Fix typos from PR 118

- config.yaml
Added vdrvergara to CoP org members, fixes #124
> Added vdrvergara to CoP org members

- config.yaml
Added sushilsuresh to CoP org members, fixes #126
> Added sushilsuresh to CoP org members

- config.yaml
Added linuxstudio to CoP member to resolve #128
> Added linuxstudio to CoP member

- config.yaml
> Added danhawker to CoP org

- config.yaml
Added darthlukan to CoP org to resolve #135
> Added darthlukan to CoP org

- config.yaml
Added trv-rpeoples to CoP for #133
> Added trv-rpeoples to CoP

- config.yaml
Per @etsauer add themoosman as a member of the MDT team.
> Add themoosman to MDT members

- config.yaml
Resolves #141 
@tylerauerbeck @jacobsee FYI
> Adding admins and mergers for the new github-actions repo

- config.yaml
Additional members to the Quay team
> Additional Quay members

- config.yaml
Added ddeno to CoP org, fixes #146
> Added ddeno to CoP org

- config.yaml
Added nstrug to CoP team for #149
> Added nstrug to CoP team

- config.yaml
New team for quay managers with admin rights
> Added new quay-mgrs team

- config.yaml
CoP member updates to resolve #152 #154 #155
> Added several members to the CoP

- config.yaml
From https://github.com/orgs/redhat-cop/teams/container-cop/members
> Add users with pending requests

- config.yaml
Added mijaros to CoP member for #159
> Added mijaros to CoP members

- config.yaml
Added leoaaraujo as CoP member for #157
> Added leoaaraujo as CoP member

- config.yaml
> Add Kurt Koller to MDT group

- config.yaml
> Added 9strands as CoP member

- ansible/inventory/group_vars/all.yml
Automation of Quay and the current state of the [redhat-cop](https://quay.io/organization/redhat-cop) Quay organization
> Added Quay management of CoP org

- config.yaml
Additional members to ninja-program-admins team to resolve #170
> Additional members to ninja-program-admins team

- config.yaml
Setup membership for `rego-policies` repository, fixes #172
> Add rego-policies repository

- config.yaml
> Added container security team

- config.yaml
Added aizuddin85 to CoP to resolve #175
> Added aizuddin85 to CoP

- config.yaml
Added repository to operators team
> Added repository to operators team

- ansible/inventory/group_vars/all.yml
New quay repositories for `group-sync-operator` and `project-initialize-operator`
> New CoP quay repositories

- config.yaml
Add new members bszeti, ckavili & lpsantil as CoP members, fixes #181, #182, #183
> Added bszeti, ckavili & lpsantil as CoP members

- ansible/inventory/group_vars/all.yml
This should make us up to date with what's in Quay.io
> Sync image repositories from Quay.io

- config.yaml
Added declarative-openshift permissions to resolve #186
> Added declarative-openshift repository permissions

- ansible/inventory/group_vars/all.yml
> Create gitlab-cleanup Quay repository

- config.yaml
Added new contributors to CoP to resolve #194 #196
> Added new contributors to CoP

- .github/workflows/quay-mgmt.yml
- ansible/playbooks/quay_management.yml
- ansible/requirements.yml
GitHub Action to manage CoP Quay.io organization
May be dependent on [https://github.com/redhat-cop/infra-ansible/pull/465](https://github.com/redhat-cop/infra-ansible/pull/465)
> Quay Workflow Management

- ansible/inventory/group_vars/all.yml
Added quay repositories or AlertManager to resolve #199
> Added quay repositories or AlertManager

- config.yaml
New team for SQL COI to resolve #200
> New team for sqlserver COI

- config.yaml
Added new contributors to CoP to resolve #204
> Add arthomasredhat as new contributor to CoP

- config.yaml
Added new contributors to CoP to resolve #208
> Add tom-stockwell as new contributor to container-cop

- config.yaml
Adds me to github-actions as a maintainer.
cc @pabrahamsson
> Added garethahealy to github-actions

- config.yaml
Resolves #211 
New repo exists here: https://github.com/redhat-cop/bats-library
@garethahealy FYI
> Permissions for new bats-library repo

- config.yaml
Added apitanga to CoP to resolve #210
> Added apitanga to CoP

- config.yaml
Added additional CoP members to resolve #219 #217
> Added CoP members

- config.yaml
Automation CoP Team permissions to resolve #203
> Automation CoP Team permissions

- config.yaml
I'm a BA CoP manager with @pamenon, so adding myself as a maintainer
> Adding new maintainer to BusinessAutomation cop

- config.yaml
@sabre1041 @oybed @pabrahamsson
> Onboard jonahkh to MDT team

- ansible/inventory/group_vars/all.yml
New quay repository global-load-balancer-operator. related to #228
> New quay repository global-load-balancer-operator

- ansible/inventory/group_vars/all.yml
ArgoCD robot account and repository for the operator
> ArgoCD robot account and repository for the operator

- config.yaml
Add new contributors to CoP, fixes #230 #231 #232
> Add new contributors to CoP

- config.yaml
Access management for rego and bats projects. Adding @ckavili and myself as suggested by @garethahealy 
https://github.com/redhat-cop/rego-policies/pull/79
https://github.com/redhat-cop/bats-library/pull/19
Thanks 😇
> 🐬 ADD - new maintainers and members for policies and bats 🐬

- config.yaml
Added Tompage1994 to CoP org to resolve #241
> Added Tompage1994 to CoP org

- ansible/inventory/group_vars/all.yml
Quay repo for github-runner-ubi8
Resolves #244
> Quay repo for github-runner-ubi8

- config.yaml
Added @redhat-cop/day-in-the-life to helm-charts repo
> Added day-life-dev to helm-charts repos

- config.yaml
Added members to day-in-the-life team to support helm charts
Related to #237
> Added members to day-in-the-life team to support helm charts

- config.yaml
@sabre1041  - this should fix the perms issue _i believe_ for @ckavili and @eformat etc
> 🐶 FIX - missing mergers for helm repo 👻

- config.yaml
Add mike lacourse to MDT project
> add malacourse

- config.yaml
Added tower_utilities team permissions to resolve #240
> Added tower_utilities team permissions

- config.yaml
Removed quay-operator-repository
> Removed quay-operator-repository

- config.yaml
Added members to automation-cop-members to resolve #255
> Added members to automation-cop-members

- config.yaml
Added alirealasad to CoP members to resolve #252
> Added alirealasad to CoP members

- config.yaml
Modifications to the @redhat-cop/operators-wg-mergers team to resolve #258
> Modifications to operators

- config.yaml
Added abhijithumbe to CoP members to resolve #262
> Added abhijithumbe to CoP members

- config.yaml
Rename tom-stockwell account to resolve #264
> Rename tom-stockwell account

- config.yaml
Added eye0fra to CoP members, fixes #268
> Added eye0fra to CoP members

- config.yaml
> Adding permissions for new babylon_agnostics repo

- config.yaml
resolves #274 
related PR #275
> Adding 'dynamic-rbac-operator' permissions

- config.yaml
Adding CoP members to resolve #278 #279
> Adding CoP members

- config.yaml
Addec Smithe2413 to CoP members, fixes #281
> Added Smithe2413 to CoP members

- config.yaml
* Added write access `namespace-configuration-operator`
* Added @cnuland to `operators-wg-mergers` team
resolves #284
> operators-wg-mergers changes

- ansible/inventory/group_vars/all.yml
- config.yaml
Support for volume-expander-operator assets to resolve #283
> Support for volume-expander-operator assets

- ansible/inventory/group_vars/all.yml
Added volume-expander-operator-controller-bundle quay repository to resolve #291
> Added volume-expander-operator-controller-bundle quay repository

- config.yaml
Added operator teams to community-operators to resolve #289
> Added operator teams to community-operators

- config.yaml
Add hfenner as CoP member to resolve #296
> Add hfenner as CoP member

- config.yaml
Permissions to support ah_configuration repository to resolve #293
> Permissions to support ah_configuration repository

- config.yaml
Permissions for automation-good-practices repository to resolve #295
> Permissions for automation-good-practices repository

- config.yaml
Added disconnectedinfra components to #297 and #298
> Added disconnectedinfra

- config.yaml
Management of new automation-cop-tower-mgrs team to resolve #302
> automation-cop-tower-mgrs team configuration

- ansible/inventory/group_vars/all.yml
Added new `operator-utils-bundle` repository related to #304
> Added operator-utils-bundle quay repository

- ansible/inventory/group_vars/all.yml
Added Quay operator bundle repositories to resolve #310 #309 #308 #307 #306
> Added operator bundle repositories

- config.yaml
> Maintenance of operators-wg-mergers team

- ansible/inventory/group_vars/all.yml
- config.yaml
proactive-node-scaling-operator considerations
> proactive-node-scaling-operator considerations

- ansible/inventory/group_vars/all.yml
Added proactive-node-scaling-operator-bundle repository to resolve #319
> Added proactive-node-scaling-operator-bundle repository

- config.yaml
Team and membership to resolve #322
> Configurations for rhel-edge-automation-arch

- config.yaml
> Removal of pelorus from CoP

- ansible/inventory/group_vars/all.yml
Added podpreset-webhook-bundle repo
> Added podpreset-webhook-bundle repo

- config.yaml
Removal of old repos and deprecation of legacy API's
> Removal of old repos and deprecation of legacy API's

- config.yaml
Added additional RHEL RFE members
> Added additional RHEL RFE members

- config.yaml
Add ryanzhang as CoP member to resolve #328
> Add ryanzhang as CoP member

- config.yaml
Added ocp-disconnected team/members to resolve #332
> Added ocp-disconnected team/members

- ansible/inventory/group_vars/all.yml
> Renamed volume-expander-operator-bundle Quay repository

- config.yaml
> Added itewk to CoP

- config.yaml
> Add chadhellyea as CoP member

- config.yaml
> Add day0hero & tosmi as CoP members

- config.yaml
> Add rflorenc & berkeragir as CoP members

- config.yaml
> Add johnsimcall as CoP member

- ansible/inventory/group_vars/all.yml
> Adding quay.io/babylon-admin & babylon team

- config.yaml
> golang CoP

- ansible/inventory/group_vars/all.yml
Added poolboy-admin Quay repository to resolve #353
> Added poolboy-admin Quay repository

- config.yaml
> Add andeahall12 and jscar-hawk as CoP members

- config.yaml
resolves #273 
@fridim FYI - please validate correct permissions/access
> Updating permissions for the newly transferred 'agnostics' repo

- config.yaml
Added classroom repo for GPTE to resolve #366
> Added classroom repo for GPTE

- config.yaml
Added varodrig to gpte team to resolve #368
> Added varodrig to gpte team

- config.yaml
> Added arvin-a to CoP

- config.yaml
Modifications for disconnected operators
> Modifications for disconnected operators

- ansible/inventory/group_vars/all.yml
> Adding quay repo for anarchy-operator

- ansible/inventory/group_vars/all.yml
> Adding quay repos for babylon-catalog-api and babylon-catalog-ui

- config.yaml
This PR, If approved, will add yvarbanov from RedHat-GPTE as member to both CoP and GPTE
> Adding yvarbanov to CoP and GPTE members

- config.yaml
> Added myself as member to container-cop-core

- config.yaml
> Permissions for community-operators-prod repository

- config.yaml
> GitOps Teams and Maintainers

- config.yaml
Added Gareth and Jared as CoP org owners
> Updated CoP owners

- config.yaml
resolves issue
distributed-working-cop #386
closes #386
> Add distributed working cop

- ansible/inventory/group_vars/all.yml
- config.yaml
Add 9strands to gpte team, resolves #398 
@fridim @jkupferer @wkulhanek @newgoliath @wkulhanek can one of you confirm?
> Add 9strands to gpte team

- config.yaml
Add vaibhavjainwiz as a CoP member, resolves #385
> Add vaibhavjainwiz as a CoP member

- config.yaml
Added jhawkinsRH to CoP to resolve #409
> :Added jhawkinsRH to CoP

- config.yaml
- https://github.com/redhat-cop/org/issues/407
- https://github.com/redhat-cop/org/issues/406
- https://github.com/redhat-cop/org/issues/405
> added members

- config.yaml
Team permissions for ee_utilities repository to resolve #413
> Team permissions for ee_utilities repository

- config.yaml
Permissions to support kube-rbac-proxy repository to resolve #416
> kube-rbac-proxy repository

- config.yaml
Adding perryrivera1, and klewis0928
> Adding 2 users to org

- config.yaml
github-workflows-operators repository configuration t resolve #424
> github-workflows-operators repository configuration

- config.yaml
Added jordigilh to RHEL RFE team
> Added jordigilh to RHEL RFE team

- ansible/inventory/group_vars/all.yml
Added patch-operator for Quay to resolve #435
> Added patch-operator for Quay

- config.yaml
Added helpernode team
Resolves #443 
Resolves #441
> Added helpernode team

- config.yaml
> Add djdanielsson as general contributor

- config.yaml
Remove jlozadad as he is no longer a GH user and add robersandovol as related to #444
> Remove jlozadad and add robersandovol

- config.yaml
> Add djdanielsson as member of automation-cop

- config.yaml
Also fix a few inconsistencies regarding the automation projects
> Add mophahr and tech2734 as automation CoP managers

- config.yaml
See #441 for original request and users
> Fix username typo, fixes #457

- config.yaml
> Add Trevor Box to operators-wg-mergers

- config.yaml
Added trevorbox to CoP members to resolve #464
> Added trevorbox to CoP members

- config.yaml
> Permissions for vault-plugin-secrets-quay

- .github/workflows/update-github-org.yml
Change from `redhat-cop-dev` to `redhat-cop`
> Update workflow to target correct org

- config.yaml
> Add APAC Automation CoP managers

- .github/workflows/quay-mgmt.yml
Corrected issues with Quay job
> Corrected issues with Quay job

- config.yaml
Access for Aleix Casanovas, new Red Hat PFE team (formerly GPTE) member.
> Add Aleix and Ahsen Shah for Babylon access

- config.yaml
* Remove itblaked from members and maintainers lists.
* Remove tech2734 from maintainers lists
* add vvaldez maintainers lists
> Update Automation CoP managers List

- .github/ISSUE_TEMPLATE/become-a-contributor.md
> added form to link gh id to rh id

- .github/ISSUE_TEMPLATE/repository-management.md
$subject - to better understand/track who are the core owners of the repo
@sabre1041 @oybed
> added block about associated cop

- config.yaml
Added davgordo to Operators Mergers
> Added davgordo to Operators Mergers

- config.yaml
Permissions for automate_fedora_desktop repository
> Permissions for automate_fedora_desktop repository

- config.yaml
Added my username to the config
> Added my username to the config

- ansible/playbooks/quay_management.yml
- config.yaml
Added new members from Service Mesh Patterns repo
> Added new members from Service Mesh Patterns repo

- config.yaml
Added service mesh patterns teams to resolve #483 
Depends on #484
> Added service mesh patterns teams

- config.yaml
Added members to appdev-cop to resolve #488
> Added members to appdev-cop

- config.yaml
Added services_catalog_configuration repository permissions to resolve #489
> Added services_catalog_configuration repository permissions

- config.yaml
Added pauljamesbrown to CoP to resolve #493
> Added pauljamesbrown to CoP

- config.yaml
> Add and update automation-cop members

- config.yaml
Fixed team name for giveback program admins
> Fixed team name for giveback program admins

- config.yaml
rename of tower_configuration_examples -> aap_configuration_template
> rename of tower_configuration_examples -> aap_configuration_template

- config.yaml
> Added members to automation-cop-tower-mgrs team

- README.md
- config.yaml
No additions or deletions were made, this simply corrects a few sorting misses.
This is in preparation for the addition of some new members.
> Simply sort the configuration

- config.yaml
Added testing CoP to resolve #509
> Added testing CoP

- config.yaml
Added rh4gsre team to resolve #516
> Added rh4gsre team

- config.yaml
Added rhdirt access to rh4gsre team to resolve #520
> Added rhdirt access to rh4gsre team

- config.yaml
Add Ansible cloud team members and validated content repo names
> Add ansible cloud team to tower managers

- config.yaml
Remove andrewwiththeredhat as user has been deleted
> Remove andrewwiththeredhat as user has been deleted

- config.yaml
Added grodideal to CoP to resolve #524
> Added grodideal to CoP

- config.yaml
Added Ansible members to CoP to resolve #527 #528 #529
> Added Ansible members to CoP

- config.yaml
Added additional members and repos to tower mgrs
> Added additional members and repos to tower mgrs

- ansible/inventory/group_vars/all.yml
- config.yaml
Added gitwebhook-operator to resolve #532
> Added gitwebhook-operator

- config.yaml
Updated username for swarred to resolve #534
> Updated username for swarred

- config.yaml
Added ansible_collections_tooling repository to resolve #537
> Added ansible_collections_tooling repository

- config.yaml
Added network.ospf for Validated Content to resolve #543
> Added network.ospf for Validated Content

- config.yaml
Added network.interfaces to Ansible Validated Content team to resolve #540
> Added network.interfaces to Ansible Validated Content team

- config.yaml
Added Chetan-07 to CoP to resolve #539
> Added Chetan-07 to CoP

- config.yaml
Add adetalhouet & strangiato as members to 'gitops-wg-mergers', fixes #547
> Add members to gitops-wg-mergers team

- config.yaml
Add 'ribua' as a new Red Hat CoP general contributor, fixes #549
> Add new member ribua

- config.yaml
> remove glimpsovstar

- config.yaml
Added neosilicon-redhat to CoP and blockchain-cop to resolve #556
> Added neosilicon-redhat to CoP and blockchain-cop

- .github/workflows/quay-mgmt.yml
- ansible/playbooks/quay_management.yml
- config.yaml
Removed NonyNo3lle from gpte team
> Removed NonyNo3lle from gpte team

- config.yaml
Added permissions for ansible-snapshot repository
> Added ansible-snapshot repository

- config.yaml
Removed prakritiverma from CoP
> Removed prakritiverma from CoP

- config.yaml
Added network.telemetry repository as validated content
Resolves #572
> Added network.telemetry repository as validated content

- config.yaml
removing ah_configuration repo to work with transfer
> removing ah_configuration repo

- config.yaml
Remove djdanielsson as he has been promoted member -> maintainer
> Removed djdanielsson from automation-cop members

- config.yaml
> Added Red Hat CoP SRE team

- config.yaml
Added ihsanmokhlisse to CoP to resolve #580
> Added ihsanmokhlisse to CoP

- config.yaml
> adding 2 new repos

- config.yaml
Added edge.microshift to validated-content-curators team to resolve #587
> Added edge.microshift to validated-content-curators team

- config.yaml
Added network.acls as validated content curators to resolve #589
> Added network.acls as validated content curators

- .github/workflows/quay-mgmt.yml
Fix Ansible Lint workflow to resolve #591
> Fix Ansible Lint workflow

- config.yaml
Removing ex Redhatters or ex-team-members from GPTE group.
> removing old gpte members mid-2023

- config.yaml
adding crenwick93 to CoP members for #595
> adding crenwick93 to CoP members

- config.yaml
Add Alberto to agnosticd-core team
> Update agnosticd-core team, add agonzalezrh

- config.yaml
agonzalezrh was not in the org but was attempted to be added as a maintainer to a repo which is causing an error in the config
> fixing error

- config.yaml
hopefully this will close this older request
> update for #597

- config.yaml
Added kincl as member of the CoP to resolve #604
> Added kincl as member of the CoP

- config.yaml
Added network.backup to Validated Content curators to resolve #602
> Added network.backup to Validated Content curators

- config.yaml
Creation of repositories and teams for Ansible ZipShip effort
> Ansible ZipShip integration

- config.yaml
> Added jeffcpullen to CoP

- config.yaml
Added rhis-builder permissions to resolve #608
> Added rhis-builder permissions

- config.yaml
Added hultzj to ansible-zipship-admins to resolve #610
> Added hultzj to ansible-zipship-admins

- config.yaml
Added ansible-zipship repo to resolve #616
> Added ansible-zipship repo

- .github/workflows/quay-mgmt.yml
Downgrade GitHub runner to mitigate ansible bug to resolve #618
> Mitigate Ansible bug for symlinks

- config.yaml
Please let me know if you all see any additional former members that should be part of this clean-up PR
CC @sabre1041
> Cleaning out former members

- config.yaml
> removed non-rh'ers

- config.yaml
Remove fostimus as this was the user causing pipelines to break
> Remove fostimus to resolve broken pipeline

- config.yaml
Added omaciel as CoP member
related to #571
> Added omaciel as CoP member

- config.yaml
Remove omaciel from CoP config
> Remove omaciel from CoP config

- .github/workflows/manage-github-org.yml
> Updated Peribolos tag

- .github/workflows/manage-github-org.yml
> Updated GHProxy image

- config.yaml
Remove ansible-snapshot-admins team
> Remove ansible-snapshot-admins team

- config.yaml
as per the others, repos are archived so team is dead
> removed distributed-working-cop team

- config.yaml
as per: https://github.com/redhat-cop/org/issues/641#issuecomment-1832224764
> removed andreahall12

- config.yaml
all the repos under that team have been achieved and migrated into another org.
> removed ansible-middleware team

- .github/workflows/config-validated.yml
- config.yaml
lowercased and sorted keyes via yq
> added pipeline to do the yq commands

- config.yaml
https://github.com/redhat-cop/org/issues/664
> added new members for ref team

- config.yaml
https://github.com/redhat-cop/org/issues/661
Needs merging before: https://github.com/redhat-cop/org/pull/665
> added ref team block

- config.yaml
wrong github usernames supplied for: https://github.com/redhat-cop/org/issues/661
@rhvinel @vbroniko
> fixed usernames for arch diagrams

- config.yaml
Added ocpv_lab and members to validated-content-curators team to resolve #668
> Added ocpv_lab and members to validated-content-curators team

- .github/ISSUE_TEMPLATE/become-a-contributor.md
> added ldap comment to become-a-contributor.md

- config.yaml
Adding Kirill Malgichev to the gpte group
> Adding makirill (Kirill Malgichev)

- config.yaml
`ansible-networking` team to resolve #700
> Created Ansible Networking team

- config.yaml
Added network.restore as validated content curators to resolve https://github.com/redhat-cop/org/issues/698
> Added network.restore as validated content curators

- config.yaml
Membership and permissions to onboard cloud.vmware_ops repository to resolve #697
> cloud.vmware_ops repository and team permissions

- config.yaml
Adding myself as a member of automerion-cop to the corresponding GH group
> add chocsrtede as automation-cop-member

- config.yaml
Added rnozaki to CoP to resolve #712
> Added rnozaki to CoP

- config.yaml
Added devspaces team to resolve #709
> Added devspaces team

- config.yaml
@murphye @skypatrolcpt @tomgeorge have ADMIN on certain repos
@k-von @kedark3 have WRITE on certain repos
All have left RH
> removed non-rhers

- config.yaml
https://github.com/redhat-cop/org/issues/722
> added r0x0d

- config.yaml
https://github.com/redhat-cop/org/issues/675
> added bkaraoren

- config.yaml
https://github.com/redhat-cop/org/issues/684
> added aap_config_as_code_docs

- config.yaml
https://github.com/redhat-cop/org/issues/728
> added chanoian

- config.yaml
there are several archived repos listed under teams that give them admin/write. it's probably a good idea to remove those permissions and only give the SRE admin. this PR does that.
> added archived team and moved all archived repos under that team

- config.yaml
Added rhel-migration team to resolve #739
> Added rhel-migration team

- config.yaml
spoke with @boogiespook on slack about archiving these 3 repos. all 3 don't have any active development and the public-facing websites have or are being sunset.
> added newly archived repos to archive team

- config.yaml
https://github.com/redhat-cop/org/issues/748
> added lpanza

- config.yaml
> Adding pacopeng

- config.yaml
closes https://github.com/redhat-cop/org/issues/678
> removed rafamqrs as no longer at RH

- ansible/inventory/group_vars/all.yml
@cgruver do you think we need any other image repos?
> Add quay images for devspaces-images repo

- config.yaml
Added p3ck to CoP members who was only added to `validated-content-curators` previously
> Added p3ck to CoP members

- config.yaml
https://github.com/redhat-cop/org/issues/772
> added neosilicon-redhat

- config.yaml
> Adding 'senthilredhat' to the org

- config.yaml
Adding @senthilredhat to the Declarative OpenShift team
> Updated team for declarative openshift

- config.yaml
https://github.com/redhat-cop/org/issues/782
> added new members to org for showroom

- config.yaml
rhel-bootc team and repositories to resolve #788
> rhel-bootc team and repositories

- config.yaml
Added ansible_rekey_variables to org to resolve #769
> Added ansible_rekey_variables to org

- config.yaml
- removed team
- added `businessautomation-cop` to archive team
> removed businessautomation-cop team

- config.yaml
> Add jritter to members list

- ansible/inventory/group_vars/all.yml
> Add devspaces-images quay repos

- config.yaml
https://github.com/redhat-cop/org/issues/791#issuecomment-2133732121
> removed berkeragir as no longer a rh

- config.yaml
https://github.com/redhat-cop/org/issues/782
> added showroom repos and members to rhis

- config.yaml
`thomasmckay` -> `tomckay@redhat.com`
> removed thomasmckay as left rh

- config.yaml
https://github.com/redhat-cop/org/issues/791
> removed chetan-07 as left rh

- config.yaml
https://github.com/redhat-cop/org/issues/825
> added rhdp-monitoring-scripts to gpte admins

- config.yaml
https://github.com/redhat-cop/org/issues/842
> added quay_configuration to validated-content-curators

- config.yaml
@herve4m as part of https://github.com/redhat-cop/org/issues/842
> added herve4m to members

- config.yaml
giving @Tompage1994 and @herve4m access to https://github.com/redhat-cop/org/issues/842
> added herve4m and tompage1994 to curated content team

- config.yaml
https://github.com/redhat-cop/org/issues/846
> added sumitridhal

- config.yaml
https://github.com/redhat-cop/org/issues/849
> added rgoodson-redhat

- config.yaml
- https://github.com/redhat-cop/org/issues/855
- https://github.com/redhat-cop/org/issues/854
> added jforce and bmarlow

- config.yaml
https://github.com/redhat-cop/org/issues/862
> added ddreggors

- config.yaml
https://github.com/redhat-cop/org/issues/838
> added partner-ecosystem-certification team

- LICENSE
- SECURITY.md
2 more checks suggested by scorecard
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#license
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy
> added security and license as suggested by scorecard

- config.yaml
https://github.com/redhat-cop/org/issues/870
> added selrahal

- .github/workflows/quay-mgmt.yml
this removes a temp fix which from looking at the linked issue is fixed now. it also solves:
- https://github.com/redhat-cop/org/security/code-scanning/5
> removed ansible install for specific version

- config.yaml
https://github.com/redhat-cop/org/issues/851
> added flightpath team

- config.yaml
closes https://github.com/redhat-cop/org/issues/851
> added rest of flightpath team

- config.yaml
https://github.com/redhat-cop/org/issues/853
> added ally-jarrett

- config.yaml
Added permissions for redhat-image-mode-demo repository to resolve #890
> Added permissions for redhat-image-mode-demo repository

- config.yaml
https://github.com/redhat-cop/org/issues/897 and https://github.com/redhat-cop/org/issues/898
> added turbra and Akasurde

- config.yaml
https://github.com/redhat-cop/org/issues/895
> removed mijaros

- config.yaml
https://github.com/redhat-cop/org/issues/904 and https://github.com/redhat-cop/org/issues/905
> added thedoubl3j and BrennanPaciorek

- config.yaml
https://github.com/redhat-cop/org/issues/903
> added infra.platform_configuration team

- config.yaml
https://github.com/redhat-cop/org/issues/914
> removed @brady-spiva and @adetalhouet

- config.yaml
> added andrew-jones and YoNoSoyVictor

- config.yaml
Added teams associated with OpenShift IaC to resolve #932 #933
> AAdded OpenShift IaC teams

- config.yaml
> Added infra.windows_ops

- config.yaml
> Removed bontreger from automation-cop members

- config.yaml
@itewk needs access to review and approve PRs to https://github.com/redhat-cop/helm-charts/tree/main/charts/operators-installer
> day-in-the-life-mergers - add itewk

- config.yaml
fixes https://github.com/redhat-cop/org/issues/947
> removed ianwatsonrh as left rh

- config.yaml
We need to add a new team member.
https://github.com/beeankha
> Add Bianca Henderson to validated content team

- config.yaml
Added nzwulfin to the CoP along with the @redhat-cop/rhel-bootc-mergers team to resolve #967
> Added nzwulfin to the CoP

- config.yaml
Provide access to redhat-image-mode-actions to bootc team
> redhat-image-mode-actions access

- ansible/inventory/group_vars/all.yml
Remove former RH users from Quay
> Remove former RH users from Quay

- config.yaml
https://github.com/redhat-cop/org/issues/979
> removed andywaltlova

- config.yaml
https://github.com/redhat-cop/org/issues/990
> removed abhijithumbe

- ansible/inventory/group_vars/all.yml
@sabre1041 @pabrahamsson @oybed OK to merge?
> added myself (garethahealy) to quay org

- config.yaml
https://github.com/redhat-cop/org/issues/987
> added gonoph

- config.yaml
As part of the Cloud Content team in Ansible, I will need to be able to update validated content that my team owns.
> Adding Chyna Sanders to the Validated Collections content team

- config.yaml
https://github.com/redhat-cop/org/issues/1002
> switched solumath to dfajmon

- README.md
After I have completely overseen what was meant with "Support", here is Mr. Explicit! :shrug:
> Make the purpose of issues more explicit

- config.yaml
Ansible Library team and repository to resolve #1021
> Ansible Library team and repository

- .github/workflows/scorecard.yml
- .github/workflows/update-github-org.yml
Especially the manage-github-org-config-workflow was creating nightly errors on my fork
I took the condition from quay-mgmt so it should be correct.
> Add condition on repository to all schedules

- ansible/inventory/group_vars/all.yml
based on https://github.com/redhat-cop/org/issues/1027#issuecomment-2729027431 - CC @cgruver
> changed cgruver to cgruver0 for quay

- config.yaml
Added mhjacks to validated-content-creators team
> Added mhjacks to validated-content-creators team

- config.yaml
https://github.com/redhat-cop/org/issues/1033
> added khalid-lemghari

- config.yaml
New maintainer for our rhel-good-practices repository.
Cheers,
Magnus
RHEL-CoP Manager
> Adding myllynen to rhel-good-practices in rhel-cop

- config.yaml
https://github.com/redhat-cop/org/issues/1061
> added kk-at-redhat

- config.yaml
https://github.com/redhat-cop/org/issues/1088
> added mahalakshmiviju
