redhat-cop/org

- config.yaml
Added maintainers and `automate-jcliff` repository to Ansible Middleware team
> Updated permissions for Ansible Middleware team

- config.yaml
As we explore using Prow we'll need to add Prow's GH user with admin/write privs to the repos we intend to use it for.
> Add Prow CI bot to ditl mergers

- config.yaml
Gareth has been a very active contributor in the pipeline-library repo and we can certainly use his help managing this repo.
He had also been added twice to day-in-the-life team hence the removal here.
> Add Gareth Healy to day-in-the-life-mergers

- config.yaml
We saw https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-org-sync-redhat-cop/309 failing with the following message after https://github.com/redhat-cop/org/pull/53 was merged.
```
msg":"Configuration failed: failed to configure redhat-cop team container-cop repos: [failed to configure redhat-cop child team operators-wg repos: [failed to update team 3299468(operators-wg) permissions on repo resource-operator-locker to read: status code 404 not one of [204], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/teams/#add-or-update-team-repository\"}]]"}
```
Looks like the name of the https://github.com/redhat-cop/resource-locker-operator repo was put in the config wrong.
/cc @sabre1041 @oybed
> Fix resource-locker-operator repo name

- config.yaml
I have no idea what these repos are, but `pelorus` is where https://github.com/redhat-cop/mdt-quickstart currenly redirects me.
Should fix https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-org-sync-redhat-cop/365#1:build-log.txt%3A269
xref: https://github.com/openshift/release/issues/6156
> mdt-quickstart was renamed to pelorus

- config.yaml
From chat:
>**Eric Sauer, 31 mins**
Petter Abrahamsson probably, but you should probably be added to that group. I think you have to be in this group: https://github.com/redhat-cop/org/blob/master/config.yaml#L3
IMO, everyone on this channel should be in that group
>
>**Petter Abrahamsson, 21 mins**
I'm happy to open a PR to add myself and JC Lopez (who seems to be the only ones missing).
>
>**Eric Sauer, 15 mins**
I would say just add yourself for now... we haven't onboarded JC into our processes yet
> Add @pabrahamsson to admins group

- config.yaml
@etsauer we are using `day-in-the-life-mergers` as our admin group so I followed this pattern as there's no `day-in-the-life-admins`.
> Migrate template2helm, fixes #103

- config.yaml
The GPTE dark-tower repo was successfully moved over today, to a new repo called `dark-tower`. The previous intended home was called `darktower`. The org permissions are hence being updated to apply to the new `dark-tower` instead. 
@tonykay FYI
> Fixing s/darktower/dark-tower permissions

- ansible/inventory/group_vars/all.yml
Adds permission definitions for the resource-dispatcher Quay repo. To go alongside https://github.com/redhat-cop/org/issues/239
> Add entry for the resource dispatcher to the group vars

- config.yaml
The `org-update-config` [job](https://prow-default.apps.ci-1.cop.rht-labs.com/?job=org-update-configs) is failing
```
{
"component":"peribolos",
"file":"prow/cmd/peribolos/main.go:201",
"func":"main.main",
"level":"fatal",
"msg":"Configuration failed: failed to configure redhat-cop team automation-cop-members repos: failed to update team 3040689(automation-cop-members) permissions on repo automate_tower_lab to write: status code 404 not one of [204], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/teams/#add-or-update-team-repository\"}",
"severity":"fatal",
"time":"2020-08-02T19:54:28Z"
}
```
Looks like the repo has been renamed
```
curl -v https://github.com/redhat-cop/automate_tower_lab 2>&1|grep location
* successfully set certificate verify …
```
> automate_tower_lab was renamed to tower_configuration_examples

- ansible/inventory/group_vars/all.yml
New infra-ansible quay.io repo to host an infra-ansible container image. 
Related infra-ansible PR: https://github.com/redhat-cop/infra-ansible/pull/543
> Adding an infra-ansible quay.io repo

- config.yaml
Peribolos is erroring on the `org-update-configs-sync` job
```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure redhat-cop team project-initializer repos: failed to configure redhat-cop child team project-initializer-mergers repos: failed to update team 3659163(project-initializer-mergers) permissions on repo project-initialize-operator to write: status code 422 not one of [204], body: {\"message\":\"Validation Failed\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions\"}","severity":"fatal","time":"2020-09-17T19:01:55Z"}
{"component":"entrypoint","error":"wrapped process failed: exit status …
```
> Fix project initialize operator team permissions

- ansible/inventory/group_vars/all.yml
Would like a new Quay repo for `dynamic-rbac-operator` stuff, when that GitHub repo gets created (#274)
> Add dynamic-rbac-operator to inventory

- config.yaml
Follow-up to PR https://github.com/redhat-cop/org/pull/277 to add an admin group
> Adding an admin group for the dynamic-rbac-operator repo

- config.yaml
This user no longer exist
>(*client).log","level":"info","msg":"UpdateOrgMembership(redhat-cop, koma-andrea, false)","time":"2021-02-26T03:46:38Z"}
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"prow/cmd/peribolos/main.go:517","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(redhat-cop, koma-andrea, false) failed","time":"2021-02-26T03:46:44Z"}
And also
```
curl -sI https://github.com/Koma-Andrea -o /dev/null -w "%{http_code}"
404
```
> Remove Koma-Andrea

- config.yaml
This should fix the following peribolos error(s)
>{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure redhat-cop team container-cop repos: [failed to configure redhat-cop child team github-actions repos: [failed to configure redhat-cop child team github-actions-mergers repos: [failed to update team 3710564(github-actions-mergers) permissions on repo github-actions to write: status code 422 not one of [204], body: {\"message\":\"Validation Failed\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions\"}]], failed to configure redhat-cop child team rego-policies repos: [failed to configure redhat-cop child team rego-policies-mergers …
> Move admin role to merger teams

- ansible/inventory/group_vars/all.yml
Repos for some of our infra monitoring prometheus exporters.
Questions:
1. Should `pushbot` be on these at all if we're going to use Quay's built-in image builder?
2. Should the team name be `prometheusexporters` or something like `prometheusexportermaintainers`? Seemed to be getting a bit long...
cc: @oybed
> Add initial repo definitions for new prometheus exporters & team for them

- config.yaml
I work in the APAC timezone and am requested to approve and assist with
maintaining items assisting jkupfere, fridim, etc.  I am adding this so that I
can approve reviews and assist with break-fix items in the code in the APAC
timezones.
> 9strands access to Babylon, etc as APAC l3 support

- .github/workflows/manage-github-org.yml
- .github/workflows/update-github-org.yml
Support the migration from prow to GH Actions
* New GitHub Secret called `PERIBOLOS_TOKEN` must be added to the repository first
* Synchronized org configuration when change pushed to `main` as well as 3am daily
> Migration of prow to GH Actions for peribolos

- config.yaml
It appears that a few repositories have been renamed which is causing Peribolos to fail.
- tower_configuration -> [controller_configuration](/redhat-cop/tower_configuration)
- tower_utilities -> [aap_utilities](/redhat-cop/tower_utilities)
```
{"component":"peribolos","file":"k8s.io/test-infra/prow/cmd/peribolos/main.go:209","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure redhat-cop team automation-cop-members repos: [failed to update team 3040689(automation-cop-members) permissions on repo tower_configuration to write: status code 404 not one of [204], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions\"},
failed to update team 3040689(automation-cop-members) …
```
> FIX: Update Peribolos config with renamed Tower repositories

- config.yaml
We need to publish helm charts in openshift-management repository in order to use it as a dependency for other helm charts. For example, using [cronjob ldap sync helm chart](https://github.com/redhat-cop/openshift-management/tree/master/charts/cronjob-ldap-group-sync) as a dependency to [FreeIPA helm chart].(https://github.com/redhat-cop/helm-charts/tree/master/charts/ipa)
In order to set up GitHub Actions to release the charts and GitHub Pages to publish them, we need to have admin access to the repository.
> 🌿add openshift-mgm repo to admin access🌿

- config.yaml
This gives the tower mgmt (ansible) team admin access to the security.firewall_mgmt repo which is validated content.
> Add firewall_mgmt to validated content/tower team

- config.yaml
Automation is failing due to missing members introduced in #519
> {"component":"peribolos","file":"k8s.io/test-infra/prow/cmd/peribolos/main.go:209","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure redhat-cop members: all team members/maintainers must also be org members: hultzj, swarren","severity":"fatal","time":"2022-11-10T11:36:58Z"}
> fix: add missing members to CoP

- config.yaml
The [CI has been failing](https://github.com/redhat-cop/org/actions/runs/3843357556/jobs/6545537003) for a while due to an incorrect username, `esolutecoder`.
This username is not in use:
```
❯ curl https://github.com/esolutecoder -so /dev/null -w %{http_code}                                     
404
❯ curl https://github.com/resolutecoder -so /dev/null -w %{http_code}                                    
200
```
This PR should fix this
> fix: Typo for resolutecoder username

- config.yaml
Repo contains validated content for Ansible on Clouds for Azure
> Add newly migrated repo cloud.azure_roles

- config.yaml
We've renamed this repo to comply with naming conventions for the Validated Content program
> Rename cloud.azure_roles repo to cloud.azure_ops

- config.yaml
Remove the smiths to fix breaking builds and no longer RH users
> Remove the smiths

- config.yaml
Repo needs to be created first, see https://github.com/redhat-cop/org/issues/639.
> Add new cloud.terraform_ops repo to validated content

- config.yaml
quay operator was migrated to the quay github org a while ago. so don't see why these teams are needed anymore
> removed quay teams as no longer needed

- config.yaml
same as others, uncontained.io is archived so the team is redundant
> removed uncontained.io from config

- config.yaml
pathfinder has been migrated to https://github.com/konveyor/tackle-pathfinder so this team is no longer needed
> removed pathfinder team

- config.yaml
Reinstate `ansible-snapshot-admins` team and resolve #649
> Reinstante ansible-snapshot-admins

- config.yaml
@mhjacks is part of a sub team but not the top level org. he keeps getting sent invitations but cant accept them for some reason. wondering if its because of this.
> added mhjacks

- config.yaml
the following members have not accepted the github invitation for join the org.
- https://github.com/orgs/redhat-cop/people/pending_invitations
username / when added to config:
- @stratus-ss : added September 2019
- @jzsjjunior : added December 2019
- @richardwalkerdev : added January 2020
- @mm7259 : added Febuary 2020
- @nstrug : added March 2020
- @krain-arnold : added March 2021
- @mbogoevici : added July 2022
- @swarred : added November 2022
as most are more than 1 year of receiving invites, presume no longer needed.
> removed members who have not accepted invitation

- config.yaml
Renamed ocpv_lab repository to support inclusion into the Validated Content program
> Renamed ocpv_lab repository

- config.yaml
the below have all left RH. GitHub says they work for someone else and their name isn't searchable in rover.
- @afflom
- @alecmerdler
- @alirealasad
- @AlyIbrahim
- @apitanga
- @arilivigni
- @cmwylie19
- @darthlukan
- @evisb
- @finmahon
- @gmontalvoy
- @jfilipcz
- @jonahkh
- @marcredhat
- @thomas-crowe
- @tomassedovic
- @truncj
- @willowmck
> removed non-rh'ers

- config.yaml
CI is broken due to:
```
Configuration failed: failed to configure redhat-cop members: all team members/maintainers must also be org members: andywaltlova, matejbuocik, monnte, solumath
```
PR fixes.
> added missing members

- config.yaml
several repos were not part of the config.yaml meaning their perms were not automated. this PR fixes that.
- https://github.com/redhat-cop/org/issues/632
> added missing repos to teams

- config.yaml
2FA is going to be enabled org wide. Once that happens, anyone without 2FA enabled will automatically be removed from the org by github.
- https://github.com/redhat-cop/org/issues/641
List is made up from:
- https://github.com/orgs/redhat-cop/people?query=two-factor%3Adisabled
- https://github.com/orgs/redhat-cop/people?query=two-factor%3Arequired
> removed people without 2fa enabled

- config.yaml
Adding members of the RHDP team to agnosticd-core team to increase coverage.
> Updating new members for Agnosticd-core membership from RHDP team

- config.yaml
Keep agnosticd-core team for core developpers:
- remove 9strands
- remove  yvarbanov
- remove d-jana
- add newgoliath
For follow the sun reasons, add to GPTE Admins:
- yvarbanov
- bbethell-1
- d-jana
> Update agnosticd-core team

- config.yaml
@ashwini-mhatre (amhatre@redhat.com) no longer in LDAP
> removed ashwini-mhatre as no longer in ldap

- config.yaml
`repo` vs `repos` - actually, i dont think it was anything to do with the teams, it was because of this typo...
- https://github.com/redhat-cop/org/issues/813
> fixed typo that is causing permissions not to be granted correctly

- config.yaml
@Monnte (pzdravec@redhat.com) is no longer showing up in LDAP, so I presume they have left RH
> removed monnte as no longer in ldap

- config.yaml
@matejbuocik never accepted the invitation and has since left RH
- https://github.com/orgs/redhat-cop/people/pending_invitations
- https://www.linkedin.com/in/matejbuocik/
> removed matejbuocik as left rh

- config.yaml
As per https://github.com/redhat-cop/org/issues/830 - I've been unable to verify who they are from LDAP, GithHub profile or LinkedIn search.
These are the last 2 people who are unknown, everyone else in the org has their GitHub ID linked to their RH ID.
> removed sbailleu and sysmatrix1 as unable to verify if redhatters

- .github/workflows/scorecard.yml
for what it is: https://github.com/ossf/scorecard?tab=readme-ov-file#what-is-scorecard
why add it? it checks for pinned actions, suggests changes to branch protection and token permission levels. overall, a good idea to run against all our repo's.
- https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-checks
> added scorecard action

- .github/workflows/config-validated.yml
- .github/workflows/manage-github-org.yml
- .github/workflows/quay-mgmt.yml
- .github/workflows/update-github-org.yml
- .gitignore
as scorecard is running on the repo, its suggested a few changes to the default token perms. this PR does that:
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
looking at the actions, I don't think the token is elevated anywhere so it shouldn't change anything but makes everything explicit.
> added default permissions for tokens

- .gitignore
- .pre-commit-config.yaml
- org-sort.sh
since we suggest using `yq` to sort/lowercase the whole config.yaml and enforce it via a github action, it might be a good idea to add a pre-commit hook that does the same job.
if someone has pre-commit installed, they can enable it. if not, life continues as-is now.
the script has a minor hack/fix in it, as there are 2 different versions of `yq` - which is why the script does the weird checking for `yq_mikefarah` at the beginning.
> added pre-commit yq sort

- config.yaml
Permissions for aap_configuration_extended and infra.controller_configuration repositories to resolve #918 #917
> Automation CoP repo permissions

- config.yaml
https://github.com/redhat-cop/org/issues/924 and fixes failing CI due to manual changes (https://github.com/redhat-cop/org/issues/924#issuecomment-2407338113).
> renamed rhis-builder-admins to rhis-code-admins

- .github/workflows/manage-github-org.yml
it seems the ghproxy/peribolos images have moved from gcr.io to pkg.dev - this updates those references.
> updated peribolos images to use new google registry

- config.yaml
CI is constantly failing because @charles-shaw is no longer a member of the CoP. I believe they have manually left and pinged via email but have not received a response.
> removed charles-shaw as manually left causing ci to fail

- config.yaml
Remove anarchy/poolboy repositories from being tracked as they are being migrated to another organization to associate with #1007
> Remove anarchy/poolboy repositories

- .gitignore
- config.yaml
This is my tentative to address issue #1009 but I'm not sure if I'm doing the right thing and I have many questions. I did my best to keep the old structures and maintainers/members, but:
1. how does the automation react to renaming teams?
2. is it necessary to have 3 levels of teams (mimicking the previous structures), couldn't we get rid of the `read` level? Doesn't anyway anybody have read level on any repo?
3. does adding the repo edge.image_mode also triggers its creation?
@sabre1041 for your attention!
> Tentative to merge the edge related teams

- .github/ISSUE_TEMPLATE/become-a-contributor.md
Updated guidance for outside contributors since existing link is not visible by non admins
> Updated guidance for outside contributors
